import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Layout from "@/components/layout/layout";
import Provider from "@/store/provider";
import { Toaster } from "sonner";

const fontRecolita = localFont({
	variable: "--font-recolita",
	src: "../../public/assets/fonts/RecoletaMedium/font.woff2",
});

const fontSofiaPro = localFont({
	variable: "--font-sofia-pro",
	src: "../../public/assets/fonts/SofiaProXLight/font.woff2",
});

// const fontPlayfairDisplay = Playfair_Display({
// 	variable: "--font-playfair-display",
// 	subsets: ["latin"],
// });

// const fontGoogleSansFlex = Google_Sans_Flex({
// 	variable: "--font-google-sans-flex",
// 	subsets: ["latin"],
// });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${fontRecolita.variable} ${fontSofiaPro.className} antialiased`}
			>
				<Provider>
					<Layout>{children}</Layout>
					<Toaster />
				</Provider>
			</body>
		</html>
	);
}
