import type { Metadata } from "next";
import { Playfair_Display, Google_Sans_Flex } from "next/font/google";
import Layout from "@/components/layout/layout";
import "./globals.css";

const fontPlayfairDisplay = Playfair_Display({
	variable: "--font-playfair-display",
	subsets: ["latin"],
});

const fontGoogleSansFlex = Google_Sans_Flex({
	variable: "--font-google-sans-flex",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${fontPlayfairDisplay.variable} ${fontGoogleSansFlex.variable} antialiased`}
			>
				<Layout>{children}</Layout>
			</body>
		</html>
	);
}
